# Generated by Django 2.1.2 on 2018-11-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='优惠券名称', max_length=255)),
                ('deleted', models.IntegerField(default=0, help_text='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名', max_length=255)),
                ('img', models.CharField(help_text='图片', max_length=255)),
                ('original_price', models.FloatField(default=0.0, help_text='原价')),
                ('actual_price', models.FloatField(help_text='实际价格')),
                ('stock', models.IntegerField(default=0, help_text='库存')),
                ('status', models.IntegerField(default=0, help_text='状态')),
                ('createtime', models.CharField(help_text='创建时间', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='等级')),
                ('name', models.CharField(help_text='等级名称', max_length=255)),
                ('devide', models.IntegerField(help_text='抽成')),
            ],
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商家名称', max_length=255)),
                ('city', models.CharField(help_text='所在城市', max_length=255)),
                ('createtime', models.CharField(help_text='创建时间', max_length=255)),
                ('level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='mall.Levels')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.FloatField(default=0.0, help_text='原价')),
                ('actual_price', models.FloatField(help_text='实际价格')),
                ('good', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='mall.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_price', models.FloatField(help_text='添加时的价格')),
                ('createtime', models.CharField(help_text='创建时间', max_length=255)),
                ('good', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='mall.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='联系人姓名', max_length=255)),
                ('phone', models.CharField(help_text='联系人电话', max_length=255)),
                ('national', models.CharField(help_text='国家', max_length=255)),
                ('province', models.CharField(help_text='省', max_length=255)),
                ('city', models.CharField(help_text='市', max_length=255)),
                ('area', models.CharField(help_text='区', max_length=255)),
                ('county', models.CharField(help_text='县/地级市', max_length=255)),
                ('township', models.CharField(help_text='乡/镇', max_length=255)),
                ('address', models.CharField(help_text='具体地址', max_length=255)),
                ('createtime', models.CharField(help_text='创建时间', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='订单号', max_length=255, unique=True)),
                ('status', models.IntegerField(default=0, help_text='状态')),
                ('total_price', models.FloatField(help_text='总价格')),
                ('actual_payment', models.FloatField(help_text='实际支付')),
                ('createtime', models.CharField(help_text='创建时间', max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Coupons')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='昵称', max_length=255)),
                ('account', models.CharField(help_text='账号', max_length=255, unique=True)),
                ('password', models.CharField(help_text='密码', max_length=255)),
                ('status', models.IntegerField(default=0, help_text='状态')),
                ('createtime', models.CharField(help_text='创建时间', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userorders',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='mall.Users'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='mall.Users'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='mall.Users'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(help_text='订单', on_delete=django.db.models.deletion.CASCADE, to='mall.UserOrders'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='mall.Users'),
        ),
        migrations.AddField(
            model_name='goods',
            name='merchant',
            field=models.ForeignKey(help_text='商家', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Merchants'),
        ),
    ]
