# Generated by Django 2.1.2 on 2018-11-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(help_text='权限')),
                ('account', models.CharField(help_text='账号', max_length=255, unique=True)),
                ('password', models.CharField(help_text='密码', max_length=255)),
                ('createtime', models.CharField(help_text='创建时间', max_length=255)),
            ],
        ),
    ]
