# Generated by Django 2.1.2 on 2018-11-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181116_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_number',
        ),
    ]
